# Compose for running NextCloud and service dependencies locally. 
version: "3.7"

services:
  lli-local-postgres:
    container_name: lli-local-postgres
    image: postgres:12
    networks:
      - lli_local
    volumes:
      - lli_ncloud_pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=localadmin
    restart: always

  lli-local-redis:
    container_name: lli-local-redis
    image: redis:alpine
    networks:
      - lli_local
    restart: always

  lli-local-ncloud:
    container_name: lli-local-ncloud
    image: ncloud:latest
    ports:
      - "80:80"
    networks:
      - lli_local
    volumes:
      - ../../../../server:/ncloud/local-source
      - lli_ncloud_conf:/ncloud/conf
      - lli_ncloud_data:/ncloud/data
    environment:
      - LLI_ENV=local
      - NGINX_PORT=80
      - NGINX_INTERNAL_HOST=localhost
      - NGINX_EXTERNAL_HOST=extern.localhost
      - NGINX_PATH_PREFIX=/foo
      - REDIS_HOST=lli-local-redis
      - REDIS_PORT=6379
      - CDSP_ADMIN_GROUPS=admin
      - CDSP_RESTRICTED_GROUPS=restricted
      - CDSP_UNASSIGNED_GROUPS=everyone
    restart: always

networks:
  lli_local:

volumes:
  lli_ncloud_conf:
  lli_ncloud_pg_data:
  lli_ncloud_data:
