name: LLI Build Pipeline

on:
  push:
    branches:
      - prod
      - uat
      - qa

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Build
      run: cd .lli && ./build.sh ncloud

    - name: Push
      run: |
        branch_name=$(echo "${GITHUB_REF#refs/heads/}")
        tag=ghcr.io/aafc-lli/ncloud:$branch_name
        docker tag ncloud $tag
        docker push $tag
