name: LLI Build Pipeline

on:
  push:
    branches:
      - feat/ncloud-modernization # TODO: rm.
      - main
      - test
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: cd .lli && ./build.sh foo
